### ISSUE TITLE
Strange issue with Contracts 0.11.0 interaction with lambdas

### ISSUE THREAD

**Issue by alexanderdean** [egonSchiele/contracts.ruby#238]
First off apologies if this has been fixed in a more recent version; we use 0.11.0 at [Snowplow](https://github.com/snowplow/snowplow).

In Snowplow we have a module function:

```ruby
      Contract String, String => Func[String, String => String]
      def self.build_fix_filenames(region, collector_format)
        return lambda { |basename, filepath|
        ...
```

Now the strange thing is that when we call the function from elsewhere in the module like:

```ruby
  fix_filenames_lambda = build_fix_filenames("foo", "bar")
```

Then the value of `fix_filenames_lambda` is set to the `Contract` - it is of class `Contract` - rather than set to the lambda (of class `Proc`).

Very odd! Removing the `Contract` assignment line fixes it.

**Comment by egonSchiele** [comment]
That's weird. [This gist](https://gist.github.com/egonSchiele/00ae31bbbad91e2423ddb688a2acfc3b) works as expected for me and prints out `2`. Does it work for you?

**Comment by alexanderdean** [comment]
Thanks for checking this @egonSchiele ! Super-weird. I took your example and ran it inside a very similar irb environment to our end-app, and it worked. I then tweaked it to make it closer to our failing code:

```ruby
require "contracts"


module Foo
  module Bar

    include Contracts

    Contract String => Func[Num => Num]
    def self.test(some_arg)
      return lambda { |x|
        return x + 1
      }
    end

    def self.print_incr
      func = test("foo")
      p func[1]
    end

  end
end

Foo.print_incr
```

That worked too. We run in JRuby - whatever is going wrong I think is very deep in the runtime...

**Comment by alex-fedorov** [comment]
Hi Alexander ,

When you actually call that function, does it work or fail (regardless of
its type)?

I'm asking since I am assuming that we are wrapping returned proc into the
contract, and contract is still callable. Maybe I'm slightly off here. Need
more input.
Alexander Dean <notifications@github.com> schrieb am Fr., 29. Juli 2016 um
7:54 PM:

**Comment by alexanderdean** [comment]
Hey @alex-fedorov - that's the odd thing, the function is not callable. In my downstream code where I try to figure out the lambda's arity, I get this error:

```
NoMethodError (undefined method `arity' for #<Contract:0x675d9d69>):
    uri:classloader:/gems/sluice-0.4.0/lib/sluice/storage/s3/s3.rb:582:in `rename_file'
    uri:classloader:/gems/sluice-0.4.0/lib/sluice/storage/s3/s3.rb:494:in `block in process_files'
    org/jruby/RubyKernel.java:1290:in `loop'
    uri:classloader:/gems/sluice-0.4.0/lib/sluice/storage/s3/s3.rb:412:in `block in process_files'
```

**Comment by waterlink** [comment]
@alexanderdean As I thought. We are wrapping lambda over here: https://github.com/egonSchiele/contracts.ruby/blob/master/lib/contracts/call_with.rb#L90-L92

Therefore calling that lambda would work just fine, but not `#arity`. I believe we are violation LSP here, we should be implementing a proper `Proc` protocol/interface for this wrapper, not just one method `#call`.

**Comment by alexanderdean** [comment]
Ah! I think I understand now. The contract on the lambda-generating function implies some kind of wrapping of the returned lambda, otherwise how can the contract of that lambda be enforced?

**Comment by waterlink** [comment]
Exactly!

**Comment by alexanderdean** [comment]
The strange thing is that this test case is working:

```ruby
require "contracts"


module Foo
  module Bar

    include Contracts

    Contract String => Func[Num => Num]
    def self.test(some_arg)
      return lambda { |x|
        return x + 1
      }
    end

    def self.print_arity
      func = test("foo")
      p func.arity
    end

  end
end

Foo.print_arity
```

Not sure what I am doing wrong...
