### ISSUE TITLE
Method validate_decorators! raises NameError

### ISSUE THREAD

**Issue by BurdetteLamar** [egonSchiele/contracts.ruby#279]
require 'contracts'
include Contracts
Contract String => String
Contract Num => String
def foo x
end

This code raises a NameError:

$ ruby foo_test.rb
c:/Ruby22/lib/ruby/gems/2.2.0/gems/contracts-0.16.0/lib/contracts/method_handler
.rb:160:in `validate_decorators!': undefined local variable or method `name' for
 #<Contracts::MethodHandler:0x1e6b100> (NameError)
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/contracts-0.16.0/lib/contracts/m
ethod_handler.rb:31:in `handle'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/contracts-0.16.0/lib/contracts/d
ecorators.rb:13:in `method_added'
        from foo_test.rb:7:in `<main>'

It should instead raise a RuntimeError with the intended message.

**Comment by BurdetteLamar** [comment]
Sorry, this is fixed here (since October).  The error is seen in the gem.  Closing.
