### ISSUE TITLE
Contracts error on private methods

### ISSUE THREAD

**Issue by cemeng** [egonSchiele/contracts.ruby#89]
It looks like contracts (0.6) breaks when contract is specified on private methods on this manner:

```ruby
require 'contracts'
include Contracts

class PrivateTest
  def say(word)
    p private_say(word)
  end

  private

  Contract String => String
  def private_say(word)
    word
  end
end

PrivateTest.new.say("Hello world")
```

Here is the stack trace:
```
/Users/cemeng/.gem/ruby/2.2.0/gems/contracts-0.6/lib/contracts/method_reference.rb:27:in `private': undefined method `PrivateTest' for class `PrivateTest' (NameError)
	from /Users/cemeng/.gem/ruby/2.2.0/gems/contracts-0.6/lib/contracts/method_reference.rb:27:in `block in make_private'
	from /Users/cemeng/.gem/ruby/2.2.0/gems/contracts-0.6/lib/contracts/method_reference.rb:27:in `class_eval'
	from /Users/cemeng/.gem/ruby/2.2.0/gems/contracts-0.6/lib/contracts/method_reference.rb:27:in `make_private'
	from /Users/cemeng/.gem/ruby/2.2.0/gems/contracts-0.6/lib/contracts/decorators.rb:174:in `common_method_added'
	from /Users/cemeng/.gem/ruby/2.2.0/gems/contracts-0.6/lib/contracts/decorators.rb:33:in `method_added'
	from private_test.rb:12:in `<class:PrivateTest>'
	from private_test.rb:4:in `<main>'
```

**Comment by alex-fedorov** [comment]
Thx for reporting, once #86 get merged, this will work properly

**Comment by cemeng** [comment]
Ah cool! Didn't notice that, I'll close this since a fix is on the way.
